#!/usr/bin/env python

import re


CONSTANT = 42

class SomeClass(object):
    def __init__(self, arg, *args, **kwargs):
        self.i = 0
        self.prog = re.compile(
            r'a+[^b]|(c)'
        )
        self.text = ('\0\x1a' r"\x7f")

def main():
    print 'Hello, world\n'

if __name__ == '__main__':
    main()
