#!/usr/bin/env python

import re


class SomeClass(object):
    def __init__(self, arg, *args, **kwargs):
        self.i = 0
        self.prog = re.compile(
            r'a+[^b]|(c)'
        )
        self.text = '\0\x1a'

def main():
    print 'Hello, world\n'

if __name__ == '__main__':
    main()
